name: rms_cloneseq_analysis_20260101
channels:
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bcftools=1.11=h7c999a4_0
  - bwa=0.7.17=h5bf99c6_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hd44998d_0
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - fastqc=0.12.1=hdfd78af_0
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - fontconfig=2.14.1=h4c34cd2_2
  - freetype=2.14.1=hf5b9546_0
  - gsl=2.6=ha341630_0
  - htslib=1.13=h9093b5e_0
  - icu=58.2=he6710b0_3
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcurl=7.87.0=h91b91d3_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20210714=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.3=he6710b0_2
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnghttp2=1.52.0=ha637b67_1
  - libpng=1.6.54=hee55ce4_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.10.3=hcbfbd50_0
  - ncurses=6.2=he6710b0_1
  - openjdk=11.0.27=hb8faadd_0
  - openssl=1.1.1w=h7f8727e_0
  - packaging=25.0=py310h06a4308_1
  - perl=5.42.0=0_h47b2149_perl5
  - pip=26.0.1=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.0=h12debd9_1
  - readline=8.1=h27cfd23_0
  - samtools=1.13=h8c37831_0
  - setuptools=80.10.2=py310h06a4308_0
  - sqlite=3.40.1=h5082296_0
  - tk=8.6.15=h54e0aa7_0
  - trimmomatic=0.40=hdfd78af_0
  - wheel=0.46.3=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxi=1.8.2=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxtst=1.2.5=h9b100fa_3
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.2.10=h5eee18b_1
  - zlib=1.2.13=hd233ad5_2
  - pip:
      - biodata==0.1.6
      - biodataplot==0.0.5
      - biodatatools==0.1.0
      - commonhelper==0.0.5
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.61.1
      - genomictools==0.0.8
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - mphelper==0.0.3
      - numpy==2.2.6
      - pandas==2.3.3
      - pillow==12.1.0
      - pybigwig==0.3.25
      - pyparsing==3.3.2
      - pysam==0.23.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scipy==1.15.3
      - simplevc==0.0.4
      - six==1.17.0
      - tzdata==2025.3
